
Build:
	gcc main.c arithematics.c factorial.c fibonacciSeries.c roots.c testUnity.c unity/unity.c -lm -Iunity
	
#for  Unity testing
Build:
	gcc arithematics.c factorial.c fibonacciSeries.c roots.c testUnity.c unity/unity.c -lm -Iunity

Run:
	./a.out
